### ISSUE TITLE
Thanks for your contributions !!!

### ISSUE THREAD

**Issue by zqgao22** [Gaffey/ExCP#2]
Dear ExCP authors,

Can you provide a training script for pre-training ViT models (even if only ViT-L) on ImageNet-1K?

We really want to follow your work, so we would like to train ViT ourselves and get a pre-training result similar to that in ExCP (about 0.71 with ViT-L32 on ImageNet-1K).

Best.

**Comment by Gaffey** [comment]
Thanks for your attention on our work. For ViT training, you can just use [timm](https://github.com/huggingface/pytorch-image-models) library to train this model, and we refer to the discussion of hyperparameters in its [issue](https://github.com/huggingface/pytorch-image-models/issues/252) with some adjustments on lr (5e-4 for 8 gpus) and batchsize (128) according to our hardware.
