### ISSUE TITLE
The compression process abruptly aborted (8*1b model)

### ISSUE THREAD

**Issue by NiuMa-1234** [Gaffey/ExCP#6]
Thank you very much for your work! I encountered a problem during the compression of 8*1b moe model and I wanna know if you encountered it on LLM and your solution. Any reply would be appreciated.

My test on Pythia-410M  works very well. But when I change the model into a 8*1b moe, the program would stop with no warning or error when there still exists some keys which have not been compressed. 
Have you encountered this problem on LLM such as llama? 

![截屏2024-07-19 16 41 10](https://github.com/user-attachments/assets/0f5ae476-90f9-45aa-872c-d08c90cbd9c9)

**Comment by Gaffey** [comment]
The printed information does not contain detailed error description. From the SIGTERM received, it can be inferred that the problem may be caused by insufficient memory. You can try to use a machine with larger memory, or try to compress different parts of the network for multiple times to avoid writing all parameters to the memory.

**Comment by NiuMa-1234** [comment]
Thank you! I've found the error, which was caused by myself... I changed the device of  KMeans from cpu to gpu but not specify the gpu id...So the program would always exit at this step. Now I'm able to compress the 8*1b model! Thank you very much!!! By the way, would the result of just 7x smaller than the original size be normal?

**Comment by Gaffey** [comment]
You may need to adjust the parameter for your model, since the distribution could be really different in MoE model. Adjust the `prune_alpha` and `prune_beta` in the `compress_pythia.py` and you may get the better compression ratio.

**Comment by NiuMa-1234** [comment]
Understood!Thank you again for your help and kindness! By the way (sorry for so many btw..), do you think the matrixed parallel compression on all keys be possible ?I found that the compression on all keys follows a same pattern so I  guess the parallel calculation might work...

**Comment by Gaffey** [comment]
The compression of each layer (or each key) in our approach is actually independent, so I think it can be parallelized.

**Comment by NiuMa-1234** [comment]
Thank you! Looking forward for your next work!
